name: 'Linux PD e2e test environment setup'
description: 'Runs different steps to setup test environment for e2e test runs.'
author: 'Vladimir Lazar'

runs:
  using: 'composite'
  steps:
    - name: Revert unprivileged user namespace restrictions
      if: runner.os == 'Linux'
      run: |
        # allow unprivileged user namespace
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      shell: bash

    - name: Install QEMU for Multi-Arch
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
      shell: bash

    - name: Set cgroup_manager to 'cgroupfs' instead of systemd
      if: runner.os == 'Linux'
      run: |
        mkdir -p ~/.config/containers
        cat <<EOT >> ~/.config/containers/containers.conf
        [engine]
        cgroup_manager="cgroupfs"
        EOT
        podman info
      shell: bash