name: Create Release on Push

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: commit-${{ github.short_sha }}
          release_name: Release ${{ github.short_sha }}
          body: |
            Automatic release created from commit ${{ github.sha }} on the main branch.
          draft: false
          prerelease: false
